version: '3'
services:
  website:
    build: .
    ports:
      - '1234:1234'
  
  database:
    image: 'mariadb'
    environment:
      MYSQL_ROOT_PASSWORD: 'test'
    volumes:
      - database-data:/virtubrick

volumes:
  database-data: